#!/usr/bin/env bash
# Wire the four-hook prek gate into the active git hooks directory.
#
# Why this script exists: the repo sets `core.hooksPath` to `.beads/hooks/` so
# beads can intercept hooks for issue sync. `prek install` refuses to run when
# `core.hooksPath` is set, so we cannot rely on the stock command. Instead we
# write a small chained block into the beads-owned pre-commit hook between
# `--- BEGIN PREK INTEGRATION ---` markers. The block is idempotent: re-runs
# replace the existing block in place.
#
# Usage:
#   bash backend/scripts/install-prek-hook.sh
#
# Acceptance: after running this, `git commit` invokes the four hooks
# (ruff check --fix, ruff format, pyright, pytest -q) and rejects bad code.

set -euo pipefail

repo_root=$(git rev-parse --show-toplevel)
cd "$repo_root"

if ! command -v prek >/dev/null 2>&1; then
  echo "error: prek not found on PATH; install via the project README." >&2
  exit 1
fi

hooks_path=$(git config --get core.hooksPath || true)

if [ -z "$hooks_path" ]; then
  exec prek install --hook-type pre-commit
fi

hook_file="$hooks_path/pre-commit"
if [ ! -f "$hook_file" ]; then
  echo "error: expected hook file at $hook_file (core.hooksPath=$hooks_path)" >&2
  exit 1
fi

block_begin="# --- BEGIN PREK INTEGRATION ---"
block_end="# --- END PREK INTEGRATION ---"
prek_block=$(cat <<EOF
$block_begin
# Chains the four-hook gate (ruff check --fix, ruff format, pyright, pytest -q)
# into the beads-managed hook because \`core.hooksPath\` makes \`prek install\`
# refuse. Generated by backend/scripts/install-prek-hook.sh — re-run the script
# to refresh.
if command -v prek >/dev/null 2>&1; then
  prek hook-impl --config .pre-commit-config.yaml --hook-type pre-commit --hook-dir "$hooks_path" -- "\$@"
  _prek_exit=\$?
  if [ \$_prek_exit -ne 0 ]; then exit \$_prek_exit; fi
fi
$block_end
EOF
)

block_file="$hook_file.prek-block.$$"
trap 'rm -f "$block_file" "$hook_file.tmp"' EXIT
printf '%s\n' "$prek_block" > "$block_file"

if grep -qF "$block_begin" "$hook_file"; then
  awk -v begin="$block_begin" -v end="$block_end" -v block_path="$block_file" '
    BEGIN {
      while ((getline line < block_path) > 0) {
        block = (block == "") ? line : block "\n" line
      }
      close(block_path)
    }
    index($0, begin) { print block; skipping = 1; next }
    skipping && index($0, end) { skipping = 0; next }
    !skipping { print }
  ' "$hook_file" > "$hook_file.tmp"
  mv "$hook_file.tmp" "$hook_file"
else
  printf '\n' >> "$hook_file"
  cat "$block_file" >> "$hook_file"
fi

chmod +x "$hook_file"
echo "installed prek chain in $hook_file"
