/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AnonymousRouteImport } from './routes/_anonymous'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnonymousSignUpRouteImport } from './routes/_anonymous/sign-up'
import { Route as AnonymousSignInRouteImport } from './routes/_anonymous/sign-in'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/app/index'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonymousRoute = AnonymousRouteImport.update({
  id: '/_anonymous',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonymousSignUpRoute = AnonymousSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AnonymousRoute,
} as any)
const AnonymousSignInRoute = AnonymousSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AnonymousRoute,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof AnonymousSignInRoute
  '/sign-up': typeof AnonymousSignUpRoute
  '/app/': typeof AuthedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof AnonymousSignInRoute
  '/sign-up': typeof AnonymousSignUpRoute
  '/app': typeof AuthedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_anonymous': typeof AnonymousRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/_anonymous/sign-in': typeof AnonymousSignInRoute
  '/_anonymous/sign-up': typeof AnonymousSignUpRoute
  '/_authed/app/': typeof AuthedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/sign-up' | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/sign-up' | '/app'
  id:
    | '__root__'
    | '/'
    | '/_anonymous'
    | '/_authed'
    | '/_anonymous/sign-in'
    | '/_anonymous/sign-up'
    | '/_authed/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnonymousRoute: typeof AnonymousRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_anonymous': {
      id: '/_anonymous'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AnonymousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_anonymous/sign-up': {
      id: '/_anonymous/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AnonymousSignUpRouteImport
      parentRoute: typeof AnonymousRoute
    }
    '/_anonymous/sign-in': {
      id: '/_anonymous/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AnonymousSignInRouteImport
      parentRoute: typeof AnonymousRoute
    }
    '/_authed/app/': {
      id: '/_authed/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AnonymousRouteChildren {
  AnonymousSignInRoute: typeof AnonymousSignInRoute
  AnonymousSignUpRoute: typeof AnonymousSignUpRoute
}

const AnonymousRouteChildren: AnonymousRouteChildren = {
  AnonymousSignInRoute: AnonymousSignInRoute,
  AnonymousSignUpRoute: AnonymousSignUpRoute,
}

const AnonymousRouteWithChildren = AnonymousRoute._addFileChildren(
  AnonymousRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppIndexRoute: AuthedAppIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnonymousRoute: AnonymousRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
